var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var t=0;return function(){return t<a.length?{done:!1,value:a[t++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var t="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return t?t.call(a):$jscomp.arrayIterator(a)};
window.mobileTables=function(a){a=a||{};var t=a.selector||"table",K=a.parseColumnIndex||function(f){return-1},L=a.hideHeadings||[],B=new WeakMap,C=new WeakMap,G=Symbol("index"),D=Symbol("hidden"),E=function(f,c){if(1===f.childNodes.length&&"#text"===f.lastChild.nodeName)return c.innerText=f.innerText,!1;for(;f.firstChild;)c.appendChild(f.firstChild);return!0},F=function(f){var c=document.createElement("tr");f.appendChild(c);return c},H=function(f,c,d){var b=c.cloneNode(!1);d&&(b.colSpan=2);E(c,b)&&
C.set(c,b);f.appendChild(b);return b},I=function(f){var c=document.createElement("div");f.replaceWith(c);return c};return function(f,c){if(f)a:{var d=c||document.querySelectorAll(t);var b=!1;d=$jscomp.makeIterator(d);for(var p=d.next();!p.done;p=d.next()){b=p.value;if(B.has(b)||b.classList.has("mobiletable-transformed")){d=void 0;break a}var v=K(b);p=I(b);var k=b,g=[],q=b.querySelector("tr"),m=0;q=$jscomp.makeIterator(q.children);for(var n=q.next();!n.done;n=q.next()){n=n.value;for(var u=n.colSpan,
e=0;e<u;){if(m===v)g.push(G);else if(L.includes(n.innerText.trim()))g.push(D);else{var z=document.createElement("td");z.innerHTML=n.innerHTML;g.push(z)}m+=1;e+=1}}u=k;v=g.indexOf(G);k=u.cloneNode(!1);m=u.querySelector("tbody").cloneNode(!1);k.appendChild(m);q=Array(g.length).fill(0);n=!0;u=$jscomp.makeIterator(u.querySelectorAll("tr"));for(e=u.next();!e.done;e=u.next())if(e=e.value,n)n=!1;else if(1===e.children.length)H(F(m),e.firstElementChild,!0);else{z=-1!==v?F(m):null;for(var l=0,y=1,w=0,J=$jscomp.makeIterator(g),
r=J.next();!r.done;r=J.next()){r=r.value;if(0<q[l])--q[l],w+=1;else{if(void 0===e.children[l-w]){console.log("mobileTables: Unsupported table layout:");console.log(e);break}if(l===v){r=z;var x=e.children[l-w],h=document.createElement("th");h.colSpan=2;h.className=x.className;E(x,h)&&C.set(x,h);r.appendChild(h)}else{x=F(m);if(r!==D){var M=x,A=r;1===A.childNodes.length&&"#text"===A.lastChild.nodeName?(h=document.createElement("td"),h.innerText=A.innerText):h=A.cloneNode(!0);M.appendChild(h)}h=e.children[l-
w].colSpan;q[l]=e.children[l-w].rowSpan-1;1===y&&(H(x,e.children[l-w],r===D).rowSpan=h);y=1===y?h:y-1;if(1<y)continue}}l+=1}}g=k;B.set(g,b);p.replaceWith(g);b.classList.add("mobiletable-transformed");b=!0}d=b}else{d=c||document.querySelectorAll(t);g=!1;d=$jscomp.makeIterator(d);for(b=d.next();!b.done;b=d.next())if(b=b.value,p=B.get(b),void 0!==p){g=I(b);v=$jscomp.makeIterator(p.querySelectorAll("td, th"));for(k=v.next();!k.done;k=v.next())k=k.value,m=C.get(k),void 0!==m&&E(m,k);g.replaceWith(p);b.classList.remove("mobiletable-transformed");
g=!0}d=g}return d}}({selector:"div.page div.mobiletable table",parseColumnIndex:function(a){a=parseInt(a.parentElement.parentElement.getAttribute("data-column"),10);return isNaN(a)||0>a?-1:a},hideHeadings:window.JSINFO.plugin_mobiletable_hideHeadings||[]});
window.checkMobileTables=function(){var a=document.querySelector("div.mobiletable");a&&(a=window.getComputedStyle(a,":before").getPropertyValue("content").replace(/"|'/g,""),window.mobileTables("mobile"===a)&&window.location.hash&&(window.location.hash=window.location.hash))};
(function(a){return["complete","interactive"].includes(document.readyState)?setTimeout(a,0):document.addEventListener("DOMContentLoaded",a)})(function(){var a;window.addEventListener("resize",function(){a&&clearTimeout(a);a=setTimeout(window.checkMobileTables,200)});window.checkMobileTables()});
